spring:
  data:
    mongodb:
      port: 0
      database: librarydb

mongock:
  runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.tikskit.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

