CREATE TABLE authors(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    surname VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_author UNIQUE (surname, name)
);

CREATE TABLE genres(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);


CREATE TABLE books(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    genre_id BIGINT NOT NULL CONSTRAINT fk_book_genre REFERENCES genres(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    author_id BIGINT NOT NULL CONSTRAINT fk_book_author REFERENCES authors(id) ON DELETE CASCADE ON UPDATE RESTRICT
);